# Generated by Django 4.2.6 on 2023-11-03 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netPay', models.FloatField()),
                ('grossPay', models.FloatField()),
                ('taxPrepayment', models.FloatField()),
                ('socialInsuranceContribution', models.FloatField()),
                ('healtInsuranceContribution', models.FloatField()),
                ('dateOfPreparation', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
