# Generated by Django 4.2.6 on 2023-11-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grossPay', models.FloatField()),
                ('pensionContributionEmployee', models.FloatField()),
                ('disabilityContributionEmployee', models.FloatField()),
                ('sicknessContributionEmployee', models.FloatField()),
                ('socialContributionsEmployee', models.FloatField()),
                ('healthInsuranceBase', models.FloatField()),
                ('healthInsuranceContribution', models.FloatField()),
                ('ppkContributionEmployee', models.FloatField()),
                ('costsOfGettingIncome', models.IntegerField()),
                ('taxableIncome', models.FloatField()),
                ('taxRate', models.IntegerField()),
                ('taxReductionAmount', models.FloatField()),
                ('incomeTax', models.FloatField()),
                ('netPay', models.FloatField()),
                ('pensionContributionEmployer', models.FloatField()),
                ('disabilityContributionEmployer', models.FloatField()),
                ('accidentContributionEmployer', models.FloatField()),
                ('laborFundContributionEmployer', models.FloatField()),
                ('ppkContributionEmployer', models.FloatField()),
                ('FGSPcontributionEmployer', models.FloatField()),
                ('employerCosts', models.FloatField()),
                ('dateOfPreparation', models.DateField(default=django.utils.timezone.now)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
