# Generated by Django 4.2.6 on 2023-11-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='healtInsuranceContribution',
            new_name='healthInsuranceContribution',
        ),
    ]
