# Generated by Django 4.2.6 on 2023-11-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0002_rename_healtinsurancecontribution_payslip_healthinsurancecontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='disabilityContribution',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='healthInsuranceContributionBasis',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='pensionContribution',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='sicknessInsuranceContribution',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='taxBasis',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='taxDue',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payslip',
            name='taxPrepayment',
            field=models.IntegerField(),
        ),
    ]
