# Generated by Django 4.2.6 on 2023-11-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0003_payslip_disabilitycontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='costsOfGettingIncome',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
