# Generated by Django 4.2.6 on 2023-11-13 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payslips', '0004_payslip_costsofgettingincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
