# Generated by Django 4.2.6 on 2023-11-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0005_payslip_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
