# Generated by Django 4.2.6 on 2023-11-13 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payslips', '0006_delete_payslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netPay', models.FloatField()),
                ('grossPay', models.FloatField()),
                ('taxBasis', models.FloatField()),
                ('taxDue', models.FloatField()),
                ('taxPrepayment', models.IntegerField()),
                ('pensionContribution', models.FloatField()),
                ('disabilityContribution', models.FloatField()),
                ('sicknessInsuranceContribution', models.FloatField()),
                ('socialInsuranceContribution', models.FloatField()),
                ('healthInsuranceContributionBasis', models.FloatField()),
                ('healthInsuranceContribution', models.FloatField()),
                ('costsOfGettingIncome', models.IntegerField()),
                ('dateOfPreparation', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
