# Generated by Django 4.2.6 on 2023-11-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='employee',
            new_name='employeeId',
        ),
    ]
